name: "CI/CD"

on: [push, pull_request]

jobs:
  es-lint:
    name: check linting (es-lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: ~/.bun/bin/bun install

      - name: Check ESLint
        run: ~/.bun/bin/bun lint

  vite:
    name: test build (vite)
    needs: [ es-lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: ~/.bun/bin/bun install

      - name: Build Vite
        run: ~/.bun/bin/bun run build
